version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"

    command: >
      sh -c "python manage.py migrate &&
        python3 manage.py wait_for_db &&
        gunicorn --bind 0:8000 --workers 5 --log-level debug proj.wsgi"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=postgres

    depends_on:
      - db
  
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine

  celery:
    build: .

    command: celery -A proj worker -l info
      
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=postgres

    depends_on:
      - db
      - redis
      - app

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./config/app.conf:/etc/nginx/conf.d/app.conf
      - ./src/static/:/static
    ports:
      - "80:80"

    depends_on:
      - app